spring.application.name=12_ONG_ENDY_PVH_SPRING_Homework003
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/homework_spring_003-db
spring.datasource.username=postgres
spring.datasource.password=endy123$$&&
spring.security.user.name=admin
spring.security.user.password=123